from sqlalchemy import Column, Date, Integer, String, Float, DateTime, ForeignKey, Boolean
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from db.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    role = Column(String) # e.g., 'farmer' or 'buyer'
    phone_number = Column(String, unique=True, index=True) # Crucial for WhatsApp/Telegram bot linking
    district = Column(String) # e.g., 'Nashik', 'Pune' - used for logistics pooling
    
    # Establish a relationship to the listings
    listings = relationship("CropListing", back_populates="farmer")

class CropListing(Base):
    __tablename__ = "crop_listings"

    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(Integer, ForeignKey("users.id"))
    crop_name = Column(String, index=True) # e.g., 'Onion', 'Tomato'
    quantity_kg = Column(Float)
    
    # AI Feature Support
    quality_grade = Column(String, nullable=True) # e.g., 'Grade A' generated by your ML model
    
    # Logistics Feature Support
    expected_price_per_kg = Column(Float)
    needs_logistics_pooling = Column(Boolean, default=False) 
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Establish the reverse relationship
    farmer = relationship("User", back_populates="listings")
    from sqlalchemy import Column, Integer, String, Float, Date, Boolean
from .database import Base
from datetime import date

# (Keep whatever existing models you already have at the top)

class TransportPool(Base):
    __tablename__ = "transport_pools"

    id = Column(Integer, primary_key=True, index=True)
    farmer_name = Column(String, index=True)
    contact_number = Column(String)
    district = Column(String, index=True)  # e.g., "Ahilyanagar", "Pune"
    crop_name = Column(String)
    weight_kg = Column(Float)
    vehicle_capacity_kg = Column(Float) # Total size of the truck they booked/need
    travel_date = Column(Date, index=True)
    is_active = Column(Boolean, default=True)